name: golangci-lint
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read

# jobs:
#   golangci:
#     name: CI Lint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: golangci-lint
#         uses: golangci/golangci-lint-action@v2
#         with:
#           # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
#           version: 'latest'
jobs:
  main:
    name: Use Golang
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang with lint
        uses: flipgroup/action-golang-with-lint@main
        with:
          version-golang: ~1.17
          version-golangci-lint: v1.43.0