on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Linux Binaries

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Linux Binaries
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        goosarch:
          - 'linux/amd64'
          #- 'linux/arm'
          #- 'linux/arm64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Get Build Matrix Info and Set Variables
        run: |
          CGO_ENABLED=1
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          CC=aarch64-linux-gnu-gcc
          PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
          BINARY_NAME=ledfx-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV


      - name: Install Dependencies
        run: |
          echo "Installing dependencies"
          sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          sudo dpkg --add-architecture $GOARCH
          sudo apt update
          sudo apt install \
            libasound-dev:$GOARCH \
            portaudio19-dev:$GOARCH \
            libportaudio2:$GOARCH \
            libportaudiocpp0:$GOARCH \
            libsamplerate0:$GOARCH \
            libsamplerate0-dev:$GOARCH \
            aubio-tools:$GOARCH \
            libaubio-dev:$GOARCH \
            libaubio-doc:$GOARCH \
      - name: Build
        run: |

          go build -o "$BINARY_NAME" -v

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}
          path: ./${{ env.BINARY_NAME }}
