name: Build linux Binaries

concurrency:
  group: ledfx-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
env:
  GHCR_SLUG: ghcr.io/spiro-c/ledfx_go
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.ledfx-cache
          key: ${{ runner.os }}-ledfx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ledfx-base-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build base (cache only)
        uses: docker/bake-action@v2
        with:
          targets: base
          set: |
            *.platform=${{ env.PLATFORMS }}
            *.cache-from=type=local,src=/tmp/.ledfx-cache
            *.cache-to=type=local,dest=/tmp/.ledfx-cache-new,mode=max
      -
        # FIXME: https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.ledfx-cache
          mv /tmp/.ledfx-cache-new /tmp/.ledfx-cache
  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64', 'linux/arm/v7', 'linux/arm/v6']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -  
        name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.ledfx-cache
          key: ${{ runner.os }}-ledfx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ledfx-base-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
                ${{ env.GHCR_SLUG }}
          tags: ${{ steps.tags.outputs.result }}
          labels: |
            org.opencontainers.image.title=ledfx 
            org.opencontainers.image.vendor=Spiro-C
      -
        name: Build artifacts
        uses: docker/bake-action@v2
        with:
          targets: artifact
          set: |
            *.platform=${{ matrix.platform }}
#      -
#        name: Move artifacts
#        run: |
#          mv ./dist/**/* ./dist/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ledfx
          path: ./dist/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            dist/*.tar.gz
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}