on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build macos Binaries
jobs:
  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        version: ['darwin-amd64', 'darwin-arm64']
        include:
          - version: darwin-amd64
            OS: darwin
            ARCH: amd64
          - version: darwin-arm64
            OS: darwin
            ARCH: arm64
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      id: go
      with:
        go-version: 1.18
        
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get Build Matrix Info and Set Variables
      run: |
        CGO_ENABLED=1
        GOOS=${{ matrix.OS }}
        GOARCH=${{ matrix.ARCH }}
        BINARY_NAME=ledfx-${{ matrix.OS }}-${{ matrix.ARCH }}
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
        echo "GOOS=$GOOS" >> $GITHUB_ENV
        echo "GOARCH=$GOARCH" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash {0}
      run: |
        if [ ${{ matrix.ARCH }} = "arm64" ]; then
          mkdir -p $HOME/arm-target/bin
          mkdir -p $HOME/arm-target/brew-cache
          echo $PWD
          export PATH="$HOME/arm-target/bin:$PATH"

          cd $HOME/arm-target
          mkdir arm-homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C arm-homebrew
          ln -s $HOME/arm-target/arm-homebrew/bin/brew $HOME/arm-target/bin/arm-brew

          export HOMEBREW_CACHE=$HOME/arm-target/brew-cache
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          arm-brew fetch --deps --bottle-tag=arm64_big_sur aubio portaudio libtool |\
            grep -E "(Downloaded to:|Already downloaded:)" |\
            grep -v pkg-config |\
            awk '{ print $3 }' |\
            xargs -n 1 arm-brew install --ignore-dependencies --force-bottle

          # Install host version of pkg-config so we can call it in the build system
          arm-brew install pkg-config
          ln -s $HOME/arm-target/arm-homebrew/bin/pkg-config $HOME/arm-target/bin/arm-pkg-config
        else
          brew install pkg-config
          brew install portaudio
          brew install aubio
        fi
    - name: Build
      run: |
        if [ ${{ matrix.ARCH }} = "arm64" ]; then
          export PKG_CONFIG_PATH=/Users/runner/arm-target/lib/pkgconfig:$PKG_CONFIG_PATH
          export AUBIO_PATH=/Users/runner/arm-target/Cellar/aubio/0.4.9_3/
          export PATH=/System/Volumes/Data/Users/runner/go/bin:$PATH
          CGO_CFLAGS="-I$AUBIO_PATH/include" CGO_LDFLAGS="-L$AUBIO_PATH/lib" CGO_ENABLED=1 GOOS=${{ matrix.OS }} GOARCH=${{ matrix.ARCH }} go build -tags dynamic -o "$BINARY_NAME" -v -ldflags="-s -w"
        else
          export PATH=/System/Volumes/Data/Users/runner/go/bin:$PATH
          CGO_ENABLED=1 GOOS=${{ matrix.OS }} GOARCH=${{ matrix.ARCH }} go build -tags dynamic -o "$BINARY_NAME" -v -ldflags="-s -w"
        fi  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BINARY_NAME }}
        path: ./${{ env.BINARY_NAME }}