on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-aubio
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         go build -o 'LedFx-windows-amd64-${{ github.sha }}.exe' -v
    - name: Package LedFx
      run: |
         export CYGPATH=$(cygpath -m /)
         mkdir LedFx_Builds/
         mv LedFx-windows-amd64-${{ github.sha }}.exe LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libaubio-5.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libportaudio.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avcodec-58.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avutil-56.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avformat-58.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfftw3-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfftw3f-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libwinpthread-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libsamplerate-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/swresample-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libmfx-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libsndfile-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libbluray-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libbz2-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgnutls-30.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgme.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libiconv-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libmodplug-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/librtmp-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libsrt.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libssh.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libaom.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libcairo-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libdav1d.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libglib-2.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgobject-2.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgsm.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libintl-8.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/liblzma-5.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libmp3lame-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libxml2-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/zlib1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libvulkan-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libopencore-amrnb-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libopencore-amrwb-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libopus-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libopenjp2-7.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/rav1e.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libFLAC.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libvorbis-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libogg-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libvorbisenc-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/librsvg-2-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libspeex-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libSvtAv1Enc.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libtheoradec-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libtheoraenc-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libvpx-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libwebpdemux-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libwebp-7.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libx264-164.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libwebpmux-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libx265.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/xvidcore.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libsoxr.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfreetype-6.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgcc_s_seh-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libstdc++-6.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libhogweed-6.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgmp-10.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libidn2-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libnettle-8.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libp11-kit-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libtasn1-6.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libunistring-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libzstd.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libcrypto-1_1-x64.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfontconfig-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpixman-1-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpng16-16.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpcre-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpixman-1-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libffi-7.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libssp-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libcairo-gobject-2.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgdk_pixbuf-2.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgio-2.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpango-1.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgomp-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpangocairo-1.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libbrotlidec.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libharfbuzz-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libexpat-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfribidi-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libthai-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libgmodule-2.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpangowin32-1.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libpangoft2-1.0-0.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libbrotlicommon.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libdatrie-1.dll LedFx_Builds/       
         cp $CYGPATH/mingw64/bin/libgraphite2.dll LedFx_Builds/       
    - name: Upload LedFx Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LedFx-windows-amd64-latest
        path: LedFx_Builds/
